# Generated by Django 3.0 on 2022-06-25 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('address_street1', models.CharField(blank=True, max_length=250, null=True)),
                ('address_street2', models.CharField(blank=True, max_length=250, null=True)),
                ('address_street3', models.CharField(blank=True, max_length=250, null=True)),
                ('address_city', models.CharField(blank=True, max_length=250, null=True)),
                ('address_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('address_state', models.CharField(blank=True, max_length=50, null=True)),
                ('address_country', models.CharField(blank=True, max_length=50, null=True)),
                ('stripe_lookup', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
