# Generated by Django 3.0 on 2022-06-27 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safe_map_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='San Francisco', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='coordinates',
            field=models.CharField(default='dfdfd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='USA', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='postal',
            field=models.CharField(default='94005', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='CA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default='Market St', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
