# Generated by Django 3.0 on 2022-06-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_map_core', '0002_auto_20220627_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RenameField(
            model_name='announcements',
            old_name='city',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street',
        ),
        migrations.AddField(
            model_name='announcements',
            name='coordinates',
            field=models.CharField(default='tbd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcements',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='safe_map_core.Profile'),
            preserve_default=False,
        ),
    ]
