# Generated by Django 3.0 on 2022-06-28 00:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('safe_map_core', '0003_auto_20220627_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='identity',
        ),
        migrations.AddField(
            model_name='extras',
            name='announcement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='safe_map_core.Announcements'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extras',
            name='childcare_support',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='extras',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extras',
            name='emergency_medical_assistance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='extras',
            name='first_aid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='extras',
            name='kid_friendly',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='extras',
            name='legal_assistance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='extras',
            name='pets',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='extras',
            name='transportation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='extras',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='safe_map_core.Profile'),
        ),
    ]
