# Generated by Django 3.0 on 2022-06-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_map_core', '0004_auto_20220627_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='languages',
            field=models.CharField(default='English', max_length=255),
            preserve_default=False,
        ),
    ]
