# Generated by Django 3.0 on 2022-06-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_map_core', '0005_announcements_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='childcare_support',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='announcements',
            name='emergency_medical_assistance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='announcements',
            name='first_aid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='announcements',
            name='kid_friendly',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='announcements',
            name='legal_assistance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='announcements',
            name='pets',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='announcements',
            name='transportation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Extras',
        ),
    ]
